# 配置dev环境
spring:
  profiles: dev
  application:
    name: abcms-eurekaServer-config

server:
  port: 8001

eureka:
  instance:
    hostname: eureka8001.com      # 指定Eureka主机
  client:
    register-with-eureka: false   # 指定是否向注册中心注册自己
    fetch-registry: false   # 指定此客户端是否能够获取eureka注册信息
    service-url:    # 暴露服务中心地址
      defaultZone: http://eureka8001.com:8001/eureka

---
# 配置test环境
spring:
  profiles: test
  application:
    name: abcms-eurekaServer-config

server:
  port: 8002

eureka:
  instance:
    hostname: eureka8002.com      # 指定Eureka主机
  client:
    register-with-eureka: false   # 指定是否向注册中心注册自己
    fetch-registry: false   # 指定此客户端是否能够获取eureka注册信息
    service-url:    # 暴露服务中心地址
      defaultZone: http://eureka8002.com:8002/eureka
